import Link from "next/link";
import {
  Brain, Mic, Code2, FileText, TrendingUp, Zap,
  ChevronRight, Star, ArrowRight, CheckCircle2,
  BarChart3, MessageSquare, Target, Sparkles
} from "lucide-react";

const FEATURES = [
  {
    icon: Mic,
    title: "Voice Mock Interviews",
    description: "Real-time AI-powered voice interviews that simulate actual interview scenarios. Get instant transcription and detailed feedback on your responses.",
    color: "from-green-500/20 to-emerald-500/10",
    border: "border-green-500/30",
  },
  {
    icon: Brain,
    title: "Adaptive AI Quiz Engine",
    description: "Dynamic question generation that adapts to your skill level. Covers DSA, system design, behavioral, and domain-specific topics.",
    color: "from-blue-500/20 to-cyan-500/10",
    border: "border-blue-500/30",
  },
  {
    icon: Code2,
    title: "Live Code Assessment",
    description: "Browser-based IDE with real-time AI hints, complexity analysis, and automated test runners. Practice in 15+ languages.",
    color: "from-purple-500/20 to-violet-500/10",
    border: "border-purple-500/30",
  },
  {
    icon: FileText,
    title: "ATS Resume Optimizer",
    description: "AI scans your resume against job descriptions, scores ATS compatibility, and rewrites weak sections to maximize callbacks.",
    color: "from-orange-500/20 to-amber-500/10",
    border: "border-orange-500/30",
  },
  {
    icon: TrendingUp,
    title: "Skill Roadmaps",
    description: "Personalized learning paths generated by AI based on your target role, current skills, and timeline. Visual node-graph view.",
    color: "from-pink-500/20 to-rose-500/10",
    border: "border-pink-500/30",
  },
  {
    icon: BarChart3,
    title: "Industry Intelligence",
    description: "Real salary data, hiring trends, in-demand skills, and company insights for your target industry — refreshed weekly.",
    color: "from-teal-500/20 to-cyan-500/10",
    border: "border-teal-500/30",
  },
];

const STATS = [
  { value: "50K+", label: "Interviews Conducted" },
  { value: "94%", label: "User Success Rate" },
  { value: "200+", label: "Skill Topics" },
  { value: "100%", label: "Free Forever" },
];

const TESTIMONIALS = [
  {
    name: "Priya Sharma",
    role: "SDE at Google",
    text: "InterviewPro's voice mock interviews felt exactly like the real thing. The AI feedback was incredibly detailed. Landed my dream job after 3 weeks!",
    rating: 5,
    avatar: "PS",
  },
  {
    name: "Arjun Mehta",
    role: "Backend Engineer at Amazon",
    text: "The code assessment feature with real-time hints was a game-changer. It helped me optimize my solutions during practice, which directly translated to interview success.",
    rating: 5,
    avatar: "AM",
  },
  {
    name: "Riya Patel",
    role: "ML Engineer at Microsoft",
    text: "The ATS resume optimizer boosted my callback rate by 60%. Got 4 interviews in the first week of using it — and it's completely free!",
    rating: 5,
    avatar: "RP",
  },
];

const ALL_FEATURES = [
  "Unlimited mock interviews",
  "Full quiz library (2000+ questions)",
  "Unlimited resumes + ATS scoring",
  "Unlimited AI career chat",
  "Advanced roadmaps + tracking",
  "Industry insights & salary data",
  "Code assessment + 15+ languages",
  "Voice interview with AI feedback",
  "Achievements & progress tracking",
  "No credit card, no limits",
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background overflow-hidden">
      {/* Nav */}
      <nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 py-4 glass border-b border-white/5">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-brand-500 flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-black" />
          </div>
          <span className="font-display font-bold text-xl text-white">InterviewPro</span>
          <span className="ml-2 px-2 py-0.5 rounded-full text-xs font-semibold bg-brand-500/20 text-brand-400 border border-brand-500/30">Free</span>
        </div>
        <div className="hidden md:flex items-center gap-8 text-sm text-white/60">
          <a href="#features" className="hover:text-white transition-colors">Features</a>
          <a href="#testimonials" className="hover:text-white transition-colors">Reviews</a>
        </div>
        <div className="flex items-center gap-3">
          <Link href="/sign-in" className="text-sm text-white/60 hover:text-white transition-colors px-3 py-1.5">
            Sign In
          </Link>
          <Link href="/sign-up" className="btn-primary text-sm">
            Get Started Free
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative pt-32 pb-20 px-6 text-center grid-bg">
        <div className="absolute inset-0 bg-gradient-radial from-brand-500/8 via-transparent to-transparent" />
        <div className="relative max-w-5xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass border border-brand-500/30 text-brand-400 text-sm font-medium mb-8 animate-fade-in">
            <Zap className="w-3.5 h-3.5" />
            100% Free · No Credit Card · No Limits
          </div>

          <h1 className="font-display text-5xl md:text-7xl font-bold text-white leading-tight mb-6 animate-fade-up">
            Ace Every Interview
            <br />
            <span className="shimmer-text">Completely Free</span>
          </h1>

          <p className="text-lg md:text-xl text-white/50 max-w-2xl mx-auto mb-10 animate-fade-up" style={{ animationDelay: "0.1s" }}>
            The most advanced AI interview preparation platform — voice mock interviews, adaptive quizzes, ATS resume optimization, and live code assessments. All free, forever.
          </p>

          <div className="flex items-center justify-center gap-4 animate-fade-up" style={{ animationDelay: "0.2s" }}>
            <Link href="/sign-up" className="btn-primary text-base px-8 py-3 flex items-center gap-2 group">
              Start Preparing Free
              <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
            <Link href="/sign-in" className="btn-secondary text-base px-8 py-3">
              Sign In
            </Link>
          </div>

          <p className="text-white/30 text-sm mt-4">No credit card · No trial · No catch</p>
        </div>

        {/* Stats */}
        <div className="max-w-3xl mx-auto mt-20 grid grid-cols-2 md:grid-cols-4 gap-6">
          {STATS.map((stat) => (
            <div key={stat.label} className="glass rounded-xl p-4 border border-white/5">
              <div className="text-2xl font-display font-bold text-brand-400">{stat.value}</div>
              <div className="text-white/40 text-sm mt-1">{stat.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="font-display text-4xl font-bold text-white mb-4">
              Everything You Need — <span className="text-brand-400">All Free</span>
            </h2>
            <p className="text-white/40 text-lg max-w-2xl mx-auto">
              Six powerful tools working together to transform you from nervous candidate to confident professional.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {FEATURES.map((feature) => {
              const Icon = feature.icon;
              return (
                <div key={feature.title} className={`relative rounded-2xl p-6 bg-gradient-to-br ${feature.color} border ${feature.border} card-hover group`}>
                  <div className="w-11 h-11 rounded-xl glass flex items-center justify-center mb-4 border border-white/10">
                    <Icon className="w-5 h-5 text-white" />
                  </div>
                  <h3 className="font-display font-semibold text-lg text-white mb-2">{feature.title}</h3>
                  <p className="text-white/50 text-sm leading-relaxed">{feature.description}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* All Included */}
      <section className="py-20 px-6 relative">
        <div className="absolute inset-0 bg-gradient-radial from-brand-500/5 via-transparent to-transparent" />
        <div className="relative max-w-3xl mx-auto text-center">
          <h2 className="font-display text-4xl font-bold text-white mb-4">
            Everything <span className="text-brand-400">Included</span>
          </h2>
          <p className="text-white/40 mb-10">No tiers, no paywalls. Create an account and get full access instantly.</p>
          <div className="glass rounded-2xl p-8 border border-brand-500/20">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {ALL_FEATURES.map((f) => (
                <div key={f} className="flex items-center gap-3 text-left">
                  <CheckCircle2 className="w-4 h-4 text-brand-500 shrink-0" />
                  <span className="text-white/70 text-sm">{f}</span>
                </div>
              ))}
            </div>
            <Link href="/sign-up" className="btn-primary mt-8 inline-flex items-center gap-2 px-8 py-3">
              Create Free Account <ChevronRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section id="testimonials" className="py-24 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="font-display text-4xl font-bold text-white mb-4">
              Stories from Our <span className="text-brand-400">Community</span>
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {TESTIMONIALS.map((t) => (
              <div key={t.name} className="glass rounded-2xl p-6 border border-white/8 card-hover">
                <div className="flex items-center gap-1 mb-4">
                  {[...Array(t.rating)].map((_, i) => (
                    <Star key={i} className="w-4 h-4 text-gold-400 fill-gold-400" />
                  ))}
                </div>
                <p className="text-white/70 text-sm leading-relaxed mb-5">"{t.text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-full bg-brand-500/20 border border-brand-500/30 flex items-center justify-center text-brand-400 font-semibold text-sm">
                    {t.avatar}
                  </div>
                  <div>
                    <div className="text-white text-sm font-medium">{t.name}</div>
                    <div className="text-white/40 text-xs">{t.role}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6">
        <div className="max-w-3xl mx-auto text-center glass rounded-3xl p-12 border border-brand-500/20 glow-green-subtle">
          <Target className="w-12 h-12 text-brand-500 mx-auto mb-4 animate-bounce-subtle" />
          <h2 className="font-display text-4xl font-bold text-white mb-4">
            Your Dream Job is <span className="shimmer-text">One Interview Away</span>
          </h2>
          <p className="text-white/50 mb-8">
            Free forever. No credit card. No limits. Just results.
          </p>
          <Link href="/sign-up" className="btn-primary text-base px-10 py-3 inline-flex items-center gap-2 group">
            Start Preparing Today — It's Free
            <ChevronRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/5 py-10 px-6 text-center text-white/30 text-sm">
        <div className="flex items-center justify-center gap-2 mb-3">
          <div className="w-6 h-6 rounded bg-brand-500/20 flex items-center justify-center">
            <Sparkles className="w-3 h-3 text-brand-500" />
          </div>
          <span className="text-white/50 font-medium">InterviewPro</span>
        </div>
        <p>© 2025 InterviewPro. Built with Next.js & Groq AI. Free forever.</p>
      </footer>
    </div>
  );
}
